<?php
	require_once 'conn.php'; //include the connection
	
	if(!empty($_FILES['image'])){ //check if the submitted form id image is not empty
		
		$image_name = $_FILES['image']['name']; //fetch the image name
		$image_temp = $_FILES['image']['tmp_name']; //fetch its temporary name auto generated by PHP
		$image_size = $_FILES['image']['size']; //fetch the image size
		
		$exp = explode(".", $image_name); //split the file name till dot
		$ext = end($exp); //fetch the end of the file name (extension)
		$allowed_ext = array('jpg', 'jpeg', 'png','PNG'); //create an array with allowed extensions
			
		if(in_array($ext, $allowed_ext)){ //if extension matches allowed
			$image = time().'.'.$ext; //generate unqiue filename with current time
			$location = "upload/".$image; //location is upload folder in same source
			if($image_size < 5242880){ //less than 5MB
				move_uploaded_file($image_temp, $location); //move the image to location
				mysqli_query($conn, "INSERT INTO `image` VALUES('', '$image', '$location')") or die(mysqli_error()); //insert into table image
				echo "success";
			}else{
				echo "error3";
			}
		}else{
			echo "error2";
		}
	}else{
		echo "error1";
	}	

?>